services:
  librespot:
    image: librespot
    build: .
    devices:
      - /dev/snd
    volumes:
      - ~/.config/pulse/cookie:/home/librespot/.pulse-cookie
    environment:
      PULSE_SERVER: 172.17.0.1
